tasks + tests 5
kudinov-fedor/python-core-training pull request #36
Opened 2024-02-14 16:48 UTC by muhaale

2024-02-14 16:50 UTC, kudinov-fedor commented on tests/anmykh/test_homework_5.py
> +    assert isinstance(param, data_type)
be carefull with identations:

```
@pytest.mark.parametrize(["param", "data_type"], [
    ({"a": 123, "b": 456, "c": 789}, dict),
    ({"a": 123, "b": 456, "c": 789}, dict),
    ({"c": 789, "a": 123, "b": 456}, dict),
    ({"a": 1, 2: "b",
      None: "abc",
      (1, "a"): "some",
      True: "kek",
      frozenset((1, 2)): "lol"}, dict)
])
def test_is_dict(param, data_type):
    assert isinstance(param, data_type)

```

2024-02-14 16:51 UTC, kudinov-fedor commented on tests/anmykh/test_homework_5.py
> +        a = 5 / 0
minimum code to fail:


```
def error_func():
    with pytest.raises(ArithmeticError):
        5 / 0

```

2024-02-14 16:51 UTC, kudinov-fedor commented on tests/anmykh/test_homework_5.py
> +    x
wrong identation, this should fail due to empty context manager body

2024-02-14 16:52 UTC, kudinov-fedor commented on tests/anmykh/test_homework_5.py
> +        a[0]
a = [].     сan be moved from with block

2024-02-14 16:52 UTC, kudinov-fedor requested changes
need to fix some comments

2024-02-15 22:58 UTC, fkudinov-mn approved these changes

2024-02-15 22:58 UTC, kudinov-fedor approved these changes

2024-02-16 15:48 UTC, merged